### Health
GET http://127.0.0.1:8000/health

### Predict
POST http://127.0.0.1:8000/predict
Content-Type: application/json

{
  "temperature": 25,
  "precipitation": 0.3,
  "visibility": 3.5,
  "hour": 18
}
